underlist/backlog/urls.py
from __future__ import absolute_import
from django.conf.urls import *
from . import views

urlpatterns = patterns('',
	url(r'^$', views.index, name = 'index'),			
	url(r'^add/$', views.add_game, name = 'add-game'),
	url(r'^edit/(?P<game_guid>\w+)/$', views.edit_game, name = 'edit-game' ),
	url(r'^delete/(?P<game_guid>\w+)/$', views.delete_game, name = 'delete-game'),
	
	url(r'^(?P<username>\w+)/(?P<game_guid>\w+)/$', views.game_detail, name='game_detail'),
	url(r'^(?P<username>\w+)/$', views.user_detail, name='user_detail'),
)

underlist/core/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^private/$', 'underlist.core.views.private', name='private'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'core/login.html'}, name='login'),
    url(r'^register/$', 'underlist.core.views.register', name='register'),
    url(r'^logout/$', 'underlist.core.views.logout_user', name='logout'),

	#Static
	url(r'^about/$', TemplateView.as_view(template_name="core/about.html")),

)

underlist/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin22/', include(admin.site.urls)),
    url(r'^', include('underlist.core.urls', namespace='core')),
	url(r'^', include('underlist.backlog.urls', namespace='backlog')),
)

urlpatterns += patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

underlist/backlog/models.py
import datetime
import markdown

from django.conf import settings
from django.db import models
from django.contrib.sites.models import Site
from django.utils.encoding import smart_unicode, smart_str
from django.utils.translation import ugettext_lazy as _

#from django.contrib.auth.models import User
from underlist.core.models import Profile as User

class GameManager(models.Manager):
		
	def unplayed(self):
		return super(GameManager, self).get_query_set().filter(status=1)

	def playing(self):
		return super(GameManager, self).get_query_set().filter(status=2)

	def completed(self):
		return super(GameManager, self).get_query_set().filter(status=3)

	def givenup(self):
		return super(GameManager, self).get_query_set().filter(status=4)

	def played(self):
		return super(GameManager, self).get_query_set().filter(status=[2,3,4])

STATUS_CHOICES = (
	(1, u'Unplayed'),
	(2, u'Playing'),
	(3, u'Completed'),	
	(4, u'Given Up'),
)
	
class Game(models.Model):
	game = models.TextField(max_length=255)
	user = models.ForeignKey(User, related_name="my_games")
	added = models.DateTimeField(verbose_name=_("Date added"), help_text=_("Time game was added to the list"), default=datetime.datetime.now)
	date_completed = models.DateTimeField(verbose_name=_("Completed date"), help_text=_("Date game was completed"), blank=True, null=True)
	is_owned = models.BooleanField(help_text=_("Should be checked if you own a copy."), default=True)
	status = models.IntegerField(choices=STATUS_CHOICES, max_length=1)
	note = models.TextField(blank=True)
	note_html = models.TextField(blank=True)

	objects = GameManager()
	
	def __unicode__(self):
		return self.game

	class Meta:
		db_table = 'backlog_games'
		verbose_name_plural = 'games'
		ordering = ('-added',)
		get_latest_by = 'added'


	def save(self, *args, **kwargs):   
		self.note_html = markdown.markdown(smart_unicode(self.note))
		super(Game, self).save(*args, **kwargs)        

underlist/core/models.py
import datetime

from django.contrib.auth.models import UserManager, AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

GENDER_CHOICES = (
	('F', _('Female')),
	('M', _('Male')),
	('P', _('Pirate')),
	('N', _('Ninja')),
	('R', _('Robot')),
)


class Profile(AbstractUser):
	gender			  = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
	location 		  = models.CharField(max_length=255, blank=True)
	url				  = models.URLField(max_length=500, blank=True)
	about			  = models.TextField(max_length=500, blank=True)
	
	#Settings
	hide_mobile       = models.BooleanField(default=False)
	last_seen_on      = models.DateTimeField(default=datetime.datetime.now)
	preferences       = models.TextField(default="{}")
	view_settings     = models.TextField(default="{}")
	send_emails       = models.BooleanField(default=False)
	is_beta			  = models.BooleanField(default=False)
	

underlist/backlog/views.py
from __future__ import absolute_import

import hashlib
import json
import functools
import datetime

from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings
from django.core import cache
from django.http import HttpResponse

from .models import Game
from underlist.core.models import Profile as User

from underlist.utils import giantbomb 
gb = giantbomb.Api('a93fd9904abaec420c9a364fa4602b45d45c2358')  

def index(request):
    if request.user.is_authenticated():
    	template = 'backlog/index.html'
    	games = Game.objects.filter(user=request.user)
    	ctx = {
    	    'unplayed' : Game.objects.unplayed().filter(user=request.user),
    	    'playing' : Game.objects.playing().filter(user=request.user),
    	    'completed' : Game.objects.completed().filter(user=request.user),
    	    'givenup' : Game.objects.givenup().filter(user=request.user),
    	}

    else:
		template = 'backlog/welcome.html'
		ctx = {}
    return render(request, template, ctx)


def user_detail(request, username):
   
    u = get_object_or_404(User, username=username)
    games = Game.objects.filter(user=u)
        
    ctx = {
        'user_obj': u,
        'email_hash': hashlib.md5(u.email).hexdigest(),
        'unplayed' : Game.objects.unplayed().filter(user=u),
        'playing' : Game.objects.playing().filter(user=u),
        'completed' : Game.objects.completed().filter(user=u),
        'givenup' : Game.objects.givenup().filter(user=u),
    }
    return render(request, "backlog/profile.html", ctx)

def game_detail(request, username, game_guid):
	game = get_object_or_404(Game, guid=game_guid)
	ctx = { 'game':game }
	return render(request, "backlog/game.html", ctx)

@login_required
def add_game(request):
	#add a game
	instance = Game(user=request.user)
	f = GameModelForm(request.POST or None, instance=instance)
	if f.is_valid():
		game = f.save(commit=False)
		game.owner = request.user
		game.save()
		messages.add_message(
			request, messages.INFO, 'Game added.')
		return redirect('index')

	ctx = {'form': f, 'adding': True}
	return render(request, 'backlog/edit-game.html', ctx) 

@login_required
def edit_game(request, game_guid):
	instance = get_object_or_404(Game, guid=game_guid, owner=request.user)
	f = GameModelForm(request.POST or None, instance=instance)
	if f.is_valid():
		game = f.save(commit=False)
		game.owner = request.user
		game.save()
		messages.add_message(
			request, messages.INFO, 'Game successfully edited.')
		return redirect('index')

	ctx = {'form': f, 'adding': False}
	return render(request, 'backlog/edit-game.html', ctx) 

@login_required
def delete_game(request, game_guid):
	game = get_object_or_404(Game, guid=game_guid, owner=request.user)
	if request.method == 'POST':
		game.delete()
		return redirect('index')
	return render(request, 'backlog/delete-confirm-game.html', {'game': game})

underlist/core/views.py
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.conf import settings

from underlist.utils import giantbomb 
gb = giantbomb.Api('a93fd9904abaec420c9a364fa4602b45d45c2358')  

def private(request):
    return TemplateResponse(request, 'core/private.html', None)

def register(request):
    if not settings.ALLOW_NEW_REGISTRATIONS:
        messages.error(request, "The admin of this service is not "
                                "allowing new registrations.")
        return HttpResponseRedirect(reverse('blobs:home'))
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you for registering, you can now '
                                      'login.')
            return HttpResponseRedirect(reverse('core:login'))
    else:
        form = UserCreationForm()

    return TemplateResponse(request, 'core/register.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect(reverse('blobs:home'))

underlist/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>underlist / {% block title %}{% endblock %}</title>
            <link rel="stylesheet" href="/static/css/bootstrap.min.css">
            <link rel="stylesheet" href="/static/css/layout.css">
    </head>
    <body>    

<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">underlist</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      {% if user.is_authenticated %}
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My collection <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Playing</a></li>
          <li><a href="#">Completed</a></li>
          <li><a href="#">Given up</a></li>
          <li><a href="#">Unplayed</a></li>
        </ul>
      </li>
      <li><a href="#">Add...</a></li>
    {% else %}
        <li><a href="{% url 'core:login' %}">Login</a></li>
        <li><a href="{% url 'core:register' %}">Register</a></li>
    {% endif %}
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
    	    		
	<div class="container" id="content">
		
        	{% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        	{% endif %}

        {% block content %}{% endblock %}
        
            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
            <script src="/static/js/bootstrap.min.js"></script>
        
	</div>
    </body>
</html>